import { mkdir, cp, writeFile, rm } from 'node:fs/promises';
import { renderPage } from '../src/render.mjs';
const html = renderPage();
await writeFile(new URL('../index.html', import.meta.url), html);
const output = new URL('../dist/', import.meta.url);
await rm(output, { recursive: true, force: true });
await mkdir(output, { recursive: true });
await writeFile(new URL('index.html', output), html);
await cp(new URL('../assets/', import.meta.url), new URL('assets/', output), { recursive: true });
await writeFile(new URL('.nojekyll', output), '');
console.log(`Built prerendered portfolio: index.html + dist/ (${Buffer.byteLength(html).toLocaleString()} bytes of HTML). No dependencies.`);
