import { profile as defaultProfile, scenarios, stack } from '../data/profile.mjs';
import { computeIllustration, icon } from './illustration.mjs';

export const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[char]));
export function safeHref(value, type='url') {
  if (typeof value !== 'string' || /[\r\n<>\[\]]/.test(value) || !value.trim()) return null;
  if (type === 'email') return /^[^\s@?&#]+@[^\s@?&#]+\.[^\s@?&#]+$/.test(value) ? `mailto:${value}` : null;
  try { const url = new URL(value); return url.protocol === 'https:' && !url.username && !url.password ? url.href : null; } catch { return null; }
}
const e = escapeHtml;
const label = (num, text, extra='') => `<div class="section-label ${extra}"><span class="label-square"></span><span>${num} / ${text}</span></div>`;
const contactLink = (p, key, text) => {
  const href = safeHref(p.contacts[key], key === 'email' ? 'email' : 'url');
  return href ? `<a class="social-link" href="${e(href)}"${key==='email'?'':' target="_blank" rel="noopener noreferrer"'}>${text}${icon('diagonal')}</a>` : `<button class="social-link unconfigured" type="button" data-channel="${key}" aria-label="${text}: not configured yet">${text}<span class="pending">Add link</span></button>`;
};
function systemDiagram() {
  const positions = [[55,115],[285,115],[515,115],[515,310],[285,310],[55,310]];
  const paths = ['M210 151H285','M440 151H515','M592 189V310','M515 346H440','M285 346H210','M132 310V189'];
  return `<div class="system-visual"><svg class="system-wires" viewBox="0 0 725 475" aria-hidden="true"><defs><pattern id="dot-grid" width="20" height="20" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".75" fill="#ffffff" opacity=".12"/></pattern></defs><rect width="725" height="475" fill="url(#dot-grid)"/><path d="M35 85H690V410H35Z" fill="none" stroke="#565d56" stroke-dasharray="4 5"/><text x="45" y="76" fill="#afb3a5" font-size="10" font-family="monospace" letter-spacing="1.3">PRIVATE INFRASTRUCTURE BOUNDARY</text>${paths.map((d,i)=>`<path d="${d}" fill="none" stroke="#576056" stroke-width="1"/><path class="packet packet-${i}" d="${d}" fill="none" stroke="#edab79" stroke-width="2.5" stroke-dasharray="7 130"/>`).join('')}<path d="M363 189V310M210 151L515 346" fill="none" stroke="#62685c" stroke-width="1" stroke-dasharray="2 6" opacity=".5"/><text x="44" y="443" fill="#838b7e" font-size="10" font-family="monospace">SCHEMATIC / NOT LIVE TELEMETRY</text></svg><div class="system-nodes">${scenarios[0].nodes.map((n,i)=>`<button type="button" class="system-node ${i===2?'core-node':''}" style="--x:${positions[i][0]/7.25}%;--y:${positions[i][1]/4.75}%" data-node="${i}" aria-describedby="node-detail"><span class="node-id">0${i+1}</span>${icon(i===2?'chip':i===3?'nodes':i===1?'shield':'direction')}<span class="node-label">${e(n.label)}</span></button>`).join('')}</div></div>`;
}
export function renderPage(p=defaultProfile) {
  const mail = safeHref(p.contacts.email, 'email');
  const canonical = safeHref(p.siteUrl);
  const json = JSON.stringify({ '@context':'https://schema.org', '@type':'Person', name:p.name, jobTitle:p.title, description:p.description, knowsLanguage:['Italian','English','French'], ...(canonical?{url:canonical}:{}), sameAs:[safeHref(p.contacts.github),safeHref(p.contacts.linkedin)].filter(Boolean) }).replace(/</g,'\\u003c');
  const config = JSON.stringify({ email:mail?p.contacts.email:'', scenarios }).replace(/</g,'\\u003c');
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark light"><meta name="theme-color" content="#171b18"><title>${e(p.name)} — AI & High-Performance Systems Architect</title><meta name="description" content="${e(p.description)}"><meta property="og:type" content="website"><meta property="og:title" content="${e(p.name)} — Intelligence, engineered."><meta property="og:description" content="${e(p.description)}">${canonical?`<link rel="canonical" href="${e(canonical)}"><meta property="og:url" content="${e(canonical)}"><meta property="og:image" content="${e(new URL('assets/social-preview.svg',canonical.endsWith('/')?canonical:canonical+'/').href)}">`:''}<meta name="twitter:card" content="summary_large_image"><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap"><link rel="stylesheet" href="assets/style.css"><script type="application/ld+json">${json}</script></head>
<body id="top"><a class="skip-link" href="#main">Skip to content</a><div class="reading-progress" aria-hidden="true"></div>
<header class="site-header"><a class="brand" href="#top" aria-label="${e(p.name)} — home"><span class="brand-symbol">n<span>.</span></span><span>${e(p.name).toUpperCase().split(' ').join('<br>')}<span class="brand-dot">*</span></span></a><nav class="desktop-nav" aria-label="Main navigation"><a href="#expertise">Expertise</a><a href="#experience">Experience</a><a href="#stack">Stack</a><a href="#contact" class="nav-contact">Let's talk ${icon('diagonal')}</a></nav><div class="header-controls"><button class="motion-toggle" type="button" aria-label="Pause animations" aria-pressed="false" title="Pause animations">${icon('pause')}</button><button class="menu-toggle" type="button" aria-label="Open navigation" aria-expanded="false" aria-controls="mobile-nav"><span></span><span></span></button></div><nav class="mobile-nav" id="mobile-nav" aria-label="Mobile navigation" hidden><a href="#expertise">Expertise ${icon('diagonal')}</a><a href="#systems">Systems ${icon('diagonal')}</a><a href="#experience">Experience ${icon('diagonal')}</a><a href="#stack">Stack ${icon('diagonal')}</a><a href="#contact">Let's talk ${icon('diagonal')}</a></nav></header>
<main id="main">
<section class="hero" aria-labelledby="hero-title"><div class="hero-gridline" aria-hidden="true"></div><div class="hero-overline"><span class="availability"><span class="status-dot"></span>Independent architect / Fractional CTO</span><span class="edition">${e(p.location).toUpperCase()} <span>↗</span> WORKING GLOBALLY</span></div><div class="hero-content"><div class="hero-copy"><p class="eyebrow">AI INFRASTRUCTURE & HIGH-PERFORMANCE SYSTEMS</p><h1 id="hero-title" aria-label="${e(p.name)} — Intelligence, engineered.">Intelligence,<br><span>engineered.</span></h1><p class="hero-description">I design the systems<br>ambitious technology runs on.</p><p class="hero-support">${e(p.description)}</p><div class="hero-actions"><button class="button button-accent" type="button" data-open-contact>Discuss your architecture ${icon('diagonal')}</button><a class="text-link" href="#systems">Explore the systems ${icon('down')}</a></div></div><div class="hero-art">${computeIllustration()}<div class="hero-art-caption"><span class="crosshair">+</span><span>FROM SILICON<br>TO SYSTEMS.</span><span class="art-scale">AXONOMETRIC VIEW<br>NOT TO SCALE</span></div></div></div><div class="hero-bottom"><span class="mono">${e(p.years)} YEARS OF ENGINEERING EXPERIENCE</span><span class="hero-bottom-center">Built for complexity. Designed for control.</span><a class="scroll-cue" href="#expertise" aria-label="Scroll to expertise">SCROLL TO EXPLORE ${icon('down')}</a></div></section>
<section class="expertise light-section" id="expertise" aria-labelledby="expertise-title"><div class="section-top">${label('01','EXPERTISE')}<span class="mono section-side">THE WHOLE SYSTEM, NOT JUST THE MODEL.</span></div><div class="expertise-intro"><h2 id="expertise-title">Complexity is inevitable.<br><span>Fragility isn't.</span></h2><div><p>Good infrastructure disappears into the work it enables.</p><p class="muted">I work across the boundaries of AI, distributed systems, and security — connecting the low-level decisions to the bigger architectural picture.</p></div></div><div class="expertise-list">${p.expertise.map((item,i)=>`<article class="expertise-row"><span class="row-number">0${i+1}</span><div class="expertise-icon">${icon(item.icon)}</div><h3>${e(item.short)}</h3><div class="expertise-copy"><h4>${e(item.title)}</h4><p>${e(item.description)}</p><span class="tool-caption">${e(item.tools)}</span></div><span class="row-arrow" aria-hidden="true">↗</span></article>`).join('')}</div></section>
<section class="systems dark-section" id="systems" aria-labelledby="systems-title"><div class="section-top">${label('02','SYSTEMS THINKING')}<span class="mono section-side"><span class="tiny-cross">+</span> ARCHITECTURE EXPLORER</span></div><div class="systems-heading"><h2 id="systems-title">See how it<br><em>connects.</em></h2><p>Different workloads. The same discipline.<br>Explore three illustrative architecture patterns.</p></div><div class="systems-workbench"><div class="scenario-tabs" role="group" aria-label="Architecture scenario">${scenarios.map((s,i)=>`<button type="button" data-scenario="${i}" aria-pressed="${i===0}" class="scenario-tab${i===0?' active':''}"><span>0${i+1}</span>${e(s.title)}${icon('diagonal')}</button>`).join('')}</div><div class="system-main"><div class="system-description" aria-live="polite" aria-atomic="true"><p class="eyebrow" id="scenario-eyebrow">${scenarios[0].eyebrow}</p><h3 id="scenario-headline">${scenarios[0].headline}</h3><p id="scenario-description">${scenarios[0].description}</p><div class="scenario-tags" id="scenario-tags">${scenarios[0].tags.map(t=>`<span>${e(t)}</span>`).join('')}</div><p class="illustration-note"><span class="status-dot"></span>Illustrative architecture</p></div><div class="system-drawing">${systemDiagram()}<p class="node-detail" id="node-detail">Select a component to inspect its role.</p></div></div></div></section>
<section class="experience light-section" id="experience" aria-labelledby="experience-title"><div class="section-top">${label('03','EXPERIENCE')}<span class="mono section-side">2015 — PRESENT</span></div><div class="experience-heading"><h2 id="experience-title">A decade inside<br><span>the infrastructure.</span></h2><p>From high-performance components<br>to enterprise-wide architecture.</p></div><div class="experience-layout"><figure class="experience-visual"><div class="photo-frame"><div class="photo-fallback" aria-hidden="true"><div class="rack-bank">${Array.from({length:5},()=>`<div class="rack">${Array.from({length:15},()=>'<i><b></b><b></b><b></b></i>').join('')}</div>`).join('')}</div><span>INFRASTRUCTURE / STUDY 01</span></div><img id="experience-image" src="${e(p.experience[0].image)}" alt="${e(p.experience[0].imageAlt)}" width="780" height="1050" loading="lazy" decoding="async"><div class="photo-overlay"><span class="mono">FIELD OF WORK / 01</span><span id="image-label">${e(p.experience[0].imageLabel)}</span><span class="photo-cross" aria-hidden="true">+</span></div></div><figcaption>Infrastructure imagery — illustrative, not client work.<br><a href="https://unsplash.com/license" target="_blank" rel="noopener noreferrer">Photography via Unsplash ↗</a></figcaption></figure><div class="experience-timeline">${p.experience.map((job,i)=>`<details class="career-item" data-career="${i}"${i===0?' open':''}><summary><span class="career-dates">${e(job.dates)}${i===0?'<span class="current-marker">Independent</span>':''}</span><span class="career-title">${e(job.title)}</span><span class="career-company">${e(job.organization)}</span><span class="career-toggle">${icon('plus')}</span></summary><div class="career-content"><p class="career-domain">${e(job.domain)}</p><p>${e(job.description)}</p><div class="career-tags">${job.tags.map(t=>`<span>${e(t)}</span>`).join('')}</div></div></details>`).join('')}<p class="career-note">Independent consulting · Enterprise infrastructure · High-performance systems</p></div></div></section>
<section class="stack dark-section" id="stack" aria-labelledby="stack-title"><div class="section-top">${label('04','TECHNICAL STACK')}<span class="mono section-side">TOOLS IN SERVICE OF THE SYSTEM.</span></div><div class="stack-heading"><h2 id="stack-title">Depth, not<br><em>a list of logos.</em></h2><p>A working toolkit across the stack.<br>Select a layer to look closer.</p></div><div class="stack-workbench"><div class="stack-filters" role="group" aria-label="Technology layer">${stack.map((g,i)=>`<button type="button" data-stack="${g.id}" aria-pressed="${i===0}" class="stack-filter${i===0?' active':''}"><span>0${i+1}</span>${e(g.title)}${icon('arrow')}</button>`).join('')}</div><div class="stack-panels">${stack.map((g,i)=>`<section class="stack-panel${i===0?' is-selected':''}" id="stack-${g.id}" aria-labelledby="stack-title-${g.id}"><div class="stack-panel-top"><h3 id="stack-title-${g.id}">${e(g.title)}</h3><span class="mono">${String(g.items.length).padStart(2,'0')} TECHNOLOGIES</span></div><p class="stack-description">${e(g.description)}</p><div class="tech-grid">${g.items.map((item,j)=>`<div class="tech-item"><span class="tech-index">${String(j+1).padStart(2,'0')}</span><h4>${e(item[0])}</h4><span class="tech-detail">${e(item[1])}</span><span class="tech-mark" aria-hidden="true">+</span></div>`).join('')}</div></section>`).join('')}</div></div><p class="standards-note">AUDIT READINESS / SOC 2 Type II · ISO 27001 · GDPR</p></section>
<section class="engagement light-section" id="engagement" aria-labelledby="engagement-title"><div class="section-top">${label('05','WORK TOGETHER')}<span class="mono section-side">B2B CONSULTING / GLOBAL ENGAGEMENTS</span></div><div class="engagement-heading"><h2 id="engagement-title">The right expertise.<br><span>At the right moment.</span></h2><p>Three ways to bring architectural<br>clarity to a difficult problem.</p></div><div class="services">${p.services.map((s,i)=>`<article class="service"><div class="service-number">0${i+1}<span>↗</span></div><h3>${e(s.title)}<span>${e(s.subtitle)}</span></h3><p>${e(s.description)}</p><div class="service-scope">${e(s.detail)}</div><button type="button" class="service-link" data-open-contact data-subject="${e(s.subject)}">Discuss this engagement ${icon('diagonal')}</button></article>`).join('')}</div><div class="language-strip"><span class="mono">CLEAR COMMUNICATION. ACROSS BORDERS.</span><div>${p.languages.map(l=>`<span>${e(l)}</span>`).join('')}</div></div></section>
<section class="contact" id="contact" aria-labelledby="contact-title"><div class="contact-top">${label('06','START A CONVERSATION')}<span class="mono">${e(p.location).toUpperCase()} / AVAILABLE GLOBALLY</span></div><div class="contact-main"><h2 id="contact-title">Have a hard<br>problem<span>?</span></h2><div class="contact-copy"><p>Let's find its<br>architecture.</p><button type="button" class="button button-dark" data-open-contact>Start a conversation ${icon('diagonal')}</button><span class="contact-format">B2B consulting · Fractional CTO · Advisory</span></div></div><div class="contact-bottom"><p>Direct channels</p><div class="contact-socials">${contactLink(p,'email','Email')}${contactLink(p,'github','GitHub')}${contactLink(p,'linkedin','LinkedIn')}</div></div><div class="contact-notice" role="status" aria-live="polite"></div><noscript><p class="contact-notice">Contact details are being configured. Project-brief tools require JavaScript.</p></noscript></section>
</main><footer class="site-footer"><a href="#top" class="footer-name">${e(p.name)}<span>© ${new Date().getUTCFullYear()}</span></a><span class="footer-tagline">PRINCIPAL AI & HIGH-PERFORMANCE SYSTEMS ARCHITECT</span><a href="#top" class="back-top">BACK TO TOP ${icon('diagonal')}</a></footer>
<dialog class="contact-dialog" aria-labelledby="dialog-title"><div class="dialog-header"><span class="eyebrow">LET'S DEFINE THE PROBLEM.</span><button type="button" data-close-contact class="dialog-close" aria-label="Close contact dialog">${icon('close')}</button></div><h2 id="dialog-title">A good system starts<br>with a good question.</h2><p class="dialog-intro">A little context is enough to start.</p><form id="brief-form"><div class="form-row"><label>Your name<input name="name" autocomplete="name" required maxlength="120" placeholder="Full name"></label><label>Your email<input name="email" type="email" autocomplete="email" required maxlength="254" placeholder="you@company.com"></label></div><label>What are you working on?<select name="engagement"><option>General architecture discussion</option>${p.services.map(s=>`<option>${e(s.subject)}</option>`).join('')}</select></label><label>The challenge<textarea name="message" rows="4" required minlength="10" maxlength="5000" placeholder="What needs to change? Where is the current system getting in the way?"></textarea></label><p class="form-honesty">${mail?'This opens a draft in your email app. Nothing is sent automatically.':'Contact details are being configured. You can prepare and copy your project brief; nothing is sent or stored.'}</p><button type="submit" class="button button-accent form-submit">${mail?'Open email draft':'Copy project brief'}${icon('diagonal')}</button><p id="form-status" class="form-status" role="status" aria-live="polite"></p><textarea id="copy-fallback" aria-label="Your project brief — select and copy" readonly hidden></textarea></form></dialog>
<script id="site-config" type="application/json">${config}</script><script id="career-config" type="application/json">${JSON.stringify(p.experience.map(j=>({image:j.image,alt:j.imageAlt,label:j.imageLabel}))).replace(/</g,'\\u003c')}</script><script src="assets/app.js" defer></script></body></html>`;
}
